//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimProval
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public Nullable<int> Structure { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.Data.Spatial.DbGeography Location { get; set; }
        public string Email { get; set; }
        public Nullable<double> DesignSpeed { get; set; }
        public string Region { get; set; }
        public Nullable<double> WindDirection { get; set; }
        public Nullable<double> Shielding { get; set; }
        public Nullable<double> TerrainCategory { get; set; }
        public Nullable<double> Topography { get; set; }
    }
}
